<Project Sdk="Microsoft.NET.Sdk.Web">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>disable</Nullable>
		<UserSecretsId>aspnet-CastleDemo-708B0CB0-0EAA-415A-87AA-60C6A98D774C</UserSecretsId>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Castle.Sdk" Version="3.0.0" />
	</ItemGroup>
</Project>
