<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <RootNamespace>CastleDemo.Framework</RootNamespace>
    <AssemblyName>CastleDemo.Framework</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <!-- net48 support is available from Castle.Sdk 3.0.0 onwards. -->
    <PackageReference Include="Castle.Sdk" Version="3.0.0" />
    <Reference Include="System.Web" />
  </ItemGroup>
</Project>
